apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: pod-redis
      labels:
        app: redis
    spec:
      containers:
      - name: redis-container
        image: redis
        resources:
          limits:
            cpu: "400m"
            memory: "512Mi"
        ports:
        - containerPort: 6379
    
    