apiVersion: v1
kind: Service
metadata: 
  name: clusterip-config-server
spec:
  selector:
    app: configserver
  type: ClusterIP
  ports:
    - name: config-server
      port: 8889
      targetPort: 8889