apiVersion: v1
kind: Service
metadata: 
  name: clusterip-postservice
spec:
  selector:
    app: postservice
  type: ClusterIP
  ports:
    - name: post-service
      port: 8070
      targetPort: 8070