apiVersion: v1
kind: Service
metadata: 
  name: clusterip-userprofileservice
spec:
  selector:
    app: userprofileservice
  type: ClusterIP
  ports:
    - name: userprofile-service
      port: 8080
      targetPort: 8080