apiVersion: v1
kind: Service
metadata: 
  name: clusterip-postgresql
spec:
  selector:
    database: postgresql
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432