apiVersion: v1
kind: Service
metadata: 
  name: loadbalancer-rabbitmq
spec:
  selector:
    app: rabbitmq
  type: LoadBalancer
  ports:
  - name: rabbitconnectiontcp
    port: 5672
    targetPort: 5672
  - name: rabbitmanagementtcp
    port: 15672
    targetPort: 15672