apiVersion: v1
kind: Service
metadata: 
  name: loadbalancer-apigatewayservice
spec:
  selector:
    app: apigatewayservice
  type: LoadBalancer
  ports:
    - name: api-gateway-service
      port: 80
      targetPort: 80