apiVersion: v1
kind: Service
metadata: 
  name: loadbalancer-authservice
spec:
  selector:
    app: authservice
  type: LoadBalancer
  ports:
    - name: auth-service
      port: 8090
      targetPort: 8090